/**
 * Constants for Moroccan universities and study fields
 * Updated for UniNest v2.0
 */

export const MOROCCAN_UNIVERSITIES = [
  'Université Mohammed V de Rabat',
  'Université Hassan II de Casablanca',
  'Université Cadi Ayyad de Marrakech',
  'Université Sidi Mohamed Ben Abdellah de Fès',
  'Université Mohammed Premier d\'Oujda',
  'Université Ibn Tofail de Kénitra',
  'Université Abdelmalek Essaâdi de Tétouan',
  'Université Hassan Premier de Settat',
  'Université Moulay Ismail de Meknès',
  'Université Sultan Moulay Slimane de Béni Mellal',
  'École Mohammadia d\'Ingénieurs (EMI)',
  'École Nationale Supérieure d\'Informatique et d\'Analyse des Systèmes (ENSIAS)',
  'Institut National des Postes et Télécommunications (INPT)',
  'École Hassania des Travaux Publics (EHTP)',
  'École Nationale d\'Architecture de Rabat',
  'ISCAE Casablanca',
  'HEM Business School',
  'Université Internationale de Rabat (UIR)',
  'Université Privée de Marrakech (UPM)',
  'EMSI - École Marocaine des Sciences de l\'Ingénieur',
];

export const STUDY_FIELDS = [
  'Computer Science',
  'Engineering',
  'Medicine',
  'Business Administration',
  'Economics',
  'Law',
  'Architecture',
  'Pharmacy',
  'Dentistry',
  'Literature',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Psychology',
  'Sociology',
  'History',
  'Geography',
  'Philosophy',
  'Languages',
  'Art & Design',
  'Communication',
  'Marketing',
  'Finance',
  'Management',
];

export const MOROCCAN_CITIES = [
  'Rabat',
  'Casablanca',
  'Marrakech',
  'Fès',
  'Oujda',
  'Kénitra',
  'Tétouan',
  'Settat',
  'Meknès',
  'Béni Mellal',
  'Agadir',
  'Tanger',
  'El Jadida',
  'Mohammedia',
  'Salé',
  'Temara',
];
